sudo: true
language: cpp
compiler: gcc
dist: trusty # Qt5, from https://gist.github.com/jreese/6207161#gistcomment-1462109

addons: 
  apt: 
    packages: libboost-all-dev

before_install:
  # Qt5, from https://gist.github.com/jreese/6207161#gistcomment-1462109
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # Qt5
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev libqt5svg5*
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  # C++14
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint.sh
  # Other GitHubs
  - ./download_other_githubs.sh

script: 
  # Build and run console
  - qmake -qt=qt5 DotMatrixConsole.pro 
  - make
  - ./DotMatrixConsole -t "Hello world"
  # Build and run desktop
  - qmake -qt=qt5 DotMatrixDesktop.pro
  - make
  - ./DotMatrixDesktop &
  - sleep 10
  - sudo killall -9 DotMatrixDesktop
  # Get code coverage
  - ./get_code_cov.sh
  - codecov
  # Call OCLint
  - ./do_oclint.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)


