sudo: require
language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-add-repository -y ppa:sonkun/sfml-development
  - sudo pip install codecov
  - sudo apt-get update -qq
  - ./install_oclint.sh

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - libboost1.55-all-dev

install: 
  - sudo apt-get install -qq g++-5  
  - sudo apt-get install libsfml-dev
  - ./download_other_githubs.sh

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
  - qmake DotMatrixConsole.pro
  - make
  - ./DotMatrixConsole -t "Hello world"
  - qmake DotMatrixDesktop.pro
  - make
  - ./DotMatrixDesktop &
  - sleep 10
  - sudo killall -9 DotMatrixDesktop
  - ./get_code_cov.sh
  - codecov
  - ./do_oclint.sh

after_success: 
  - bash <(curl -s https://codecov.io/bash)

