sudo: require
language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-add-repository -y ppa:sonkun/sfml-development
  - sudo pip install codecov
  - sudo apt-get update -qq

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - libboost1.55-all-dev

install: 
  - sudo apt-get install -qq g++-5  
  - sudo apt-get install libsfml-dev

before_script:
  - ./download_other_githubs.sh

script: 
  - ./build_console.sh
  - ./build_desktop.sh
  - ./get_code_cov.sh
  - codecov

after_success: 
  - bash <(curl -s https://codecov.io/bash)

