language: cpp
dist: bionic
compiler: gcc

install:
  - sudo apt update -qq
  # Boost
  - sudo apt install libboost-all-dev
  # Qt5
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev libqt5svg5*
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint.sh
  # Other GitHubs
  - ./download_other_githubs.sh

services:
  - xvfb

script: 
  # Build and run console
  - qmake -qt=qt5 DotMatrixConsole.pro 
  - make --silent
  - ./DotMatrixConsole -t "Hello world"
  # Build and run desktop
  - qmake -qt=qt5 DotMatrixDesktop.pro
  - make --silent
  - ./DotMatrixDesktop &
  - sleep 10
  - sudo killall -9 DotMatrixDesktop
  # Get code coverage
  - ./get_code_cov.sh >/dev/null
  - codecov >/dev/null
  # Call OCLint
  - ./do_oclint.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
